<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	  <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	  <RootNamespace>GBRGBDump.WebServer</RootNamespace>
	  <IsPackable>false</IsPackable>
	  <UserSecretsId>25fd51a8-74ab-4ae2-a933-8929ef19ce2a</UserSecretsId>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="settings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.7.2" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GBRGBDump.Web.Shared\GBRGBDump.Web.Shared.csproj" />
    <ProjectReference Include="..\GBTools.Bootstrapper\GBTools.Bootstrapper.csproj" />
    <ProjectReference Include="..\GBTools.Common\GBTools.Common.csproj" />
    <ProjectReference Include="..\GBTools.Decoder\GBTools.Decoder.csproj" />
    <ProjectReference Include="..\GBTools.Graphics\GBTools.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
