<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <None Include="ffmpeg-video-args.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GBTools.GBxCart.Serial\GBTools.GBxCart.Serial.csproj" />
    <ProjectReference Include="..\GBTools.ImageSharp.GameBoyCamera\GBTools.ImageSharp.GameBoyCamera.csproj" />
    <ProjectReference Include="..\GBTools.ImageSharp.GameBoyCamera.Lite\GBTools.ImageSharp.GameBoyCamera.Lite.csproj" />
    <ProjectReference Include="..\GBTools.PicoGbPrinter.Serial\GBTools.PicoGbPrinter.Serial.csproj" />
    <ProjectReference Include="..\GBTools.PicNRec.Serial\GBTools.PicNRec.Serial.csproj" />
  </ItemGroup>
</Project>
