name: Build and Release .NET App

on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
concurrency: production
permissions: 
  contents: write
  packages: write
  attestations: write
  id-token: write

env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  NUGET_OWNER: MaddoScientisto

jobs:
  # GitVersion_v6_cross_job:
  #   name: GitVersion v6 (cross job)
  #   runs-on: ubuntu-latest
  #   outputs:
  #     branchName: ${{ steps.version_step.outputs.branchName }}
  #     fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

  #     GitVersion_BranchName: ${{ steps.version_step.outputs.GitVersion_BranchName }}
  #     GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Install GitVersion
  #       uses: gittools/actions/gitversion/setup@v3.0.0
  #       with:
  #         versionSpec: '6.x'

  #     - name: Determine Version
  #       id: version_step # step id used as reference for output values
  #       uses: gittools/actions/gitversion/execute@v3.0.0     

  build-gbrgbdump-gui:
    runs-on: ubuntu-latest
    outputs:
       branchName: ${{ steps.version_step.outputs.branchName }}
       fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        global-json-file: ./global.json
        dotnet-version: '10.0.202'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Add NuGet package source
      run : |
        dotnet nuget add source --username ${{ env.NUGET_OWNER }} --store-password-in-clear-text --password ${{ env.NUGET_APIKEY }} --name maddo-github "https://nuget.pkg.github.com/${{ env.NUGET_OWNER }}/index.json"    
    
    # Debug step
    - name: Display structure of downloaded files
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore --locked-mode ./GBRGBDump.slnx

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.2
      with:
        versionSpec: '6.0.x'

    - name: Determine Version
      id: version_step # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.1.2

    - name: Update Version
      uses: gittools/actions/gitversion/command@v3.1.2
      with:
        arguments: /updateprojectfiles

    # Build Executables

    - name: Build release binaries
      shell: bash
      run: |
        declare -a publish_targets=(
          "GBTools.ImageSharp.GameBoyCamera.Avalonia ./GBTools.ImageSharp.GameBoyCamera.Avalonia/GBTools.ImageSharp.GameBoyCamera.Avalonia.csproj win-x64"
          "GBTools.ImageSharp.GameBoyCamera.Avalonia ./GBTools.ImageSharp.GameBoyCamera.Avalonia/GBTools.ImageSharp.GameBoyCamera.Avalonia.csproj win-arm64"
          "GBTools.ImageSharp.GameBoyCamera.Avalonia ./GBTools.ImageSharp.GameBoyCamera.Avalonia/GBTools.ImageSharp.GameBoyCamera.Avalonia.csproj linux-x64"
          "GBTools.ImageSharp.GameBoyCamera.Avalonia ./GBTools.ImageSharp.GameBoyCamera.Avalonia/GBTools.ImageSharp.GameBoyCamera.Avalonia.csproj linux-arm64"
          "GBTools.PicNRec.Serial.Console ./GBTools.PicNRec.Serial.Console/GBTools.PicNRec.Serial.Console.csproj win-x64"
          "GBTools.PicNRec.Serial.Console ./GBTools.PicNRec.Serial.Console/GBTools.PicNRec.Serial.Console.csproj win-arm64"
          "GBTools.PicNRec.Serial.Console ./GBTools.PicNRec.Serial.Console/GBTools.PicNRec.Serial.Console.csproj linux-x64"
          "GBTools.PicNRec.Serial.Console ./GBTools.PicNRec.Serial.Console/GBTools.PicNRec.Serial.Console.csproj linux-arm64"
        )

        for target in "${publish_targets[@]}"; do
          read -r output_name project_path runtime <<< "$target"
          dotnet publish "$project_path" --configuration Release --runtime "$runtime" --self-contained true -p:PublishSingleFile=true --output "publish/$output_name/$runtime"
        done

    - name: Build static web app
      run: |
        dotnet publish ./GBRGBDump.Web.Static/GBRGBDump.Web.Static.csproj --configuration Release --output publish/GBRGBDump.Web.Static

    # Build NuGet Packages
    - run: |
        dotnet pack ./GBTools.ImageSharp.GameBoyCamera/GBTools.ImageSharp.GameBoyCamera.csproj -v d --configuration Release --output ${{ env.NuGetDirectory }}
        dotnet pack ./GBTools.ImageSharp.GameBoyCamera.Lite/GBTools.ImageSharp.GameBoyCamera.Lite.csproj -v d --configuration Release --output ${{ env.NuGetDirectory }}
        dotnet pack ./GBTools.PicNRec.Serial/GBTools.PicNRec.Serial.csproj -v d --configuration Release --output ${{ env.NuGetDirectory }}

    # Upload NuGet Packages Artifacts
    - name: Upload NuGet Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}/*.nupkg
        if-no-files-found: error

    # Upload Artifacts

    - name: Upload Avalonia Artifact win-x64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.ImageSharp.GameBoyCamera.Avalonia-win-x64
        path: publish/GBTools.ImageSharp.GameBoyCamera.Avalonia/win-x64/**
        if-no-files-found: error

    - name: Upload Avalonia Artifact win-arm64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.ImageSharp.GameBoyCamera.Avalonia-win-arm64
        path: publish/GBTools.ImageSharp.GameBoyCamera.Avalonia/win-arm64/**
        if-no-files-found: error

    - name: Upload Avalonia Artifact linux-x64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.ImageSharp.GameBoyCamera.Avalonia-linux-x64
        path: publish/GBTools.ImageSharp.GameBoyCamera.Avalonia/linux-x64/**
        if-no-files-found: error

    - name: Upload Avalonia Artifact linux-arm64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.ImageSharp.GameBoyCamera.Avalonia-linux-arm64
        path: publish/GBTools.ImageSharp.GameBoyCamera.Avalonia/linux-arm64/**
        if-no-files-found: error

    - name: Upload PicNRec Console Artifact win-x64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.PicNRec.Serial.Console-win-x64
        path: publish/GBTools.PicNRec.Serial.Console/win-x64/**
        if-no-files-found: error

    - name: Upload PicNRec Console Artifact win-arm64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.PicNRec.Serial.Console-win-arm64
        path: publish/GBTools.PicNRec.Serial.Console/win-arm64/**
        if-no-files-found: error

    - name: Upload PicNRec Console Artifact linux-x64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.PicNRec.Serial.Console-linux-x64
        path: publish/GBTools.PicNRec.Serial.Console/linux-x64/**
        if-no-files-found: error

    - name: Upload PicNRec Console Artifact linux-arm64
      uses: actions/upload-artifact@v4
      with:
        name: GBTools.PicNRec.Serial.Console-linux-arm64
        path: publish/GBTools.PicNRec.Serial.Console/linux-arm64/**
        if-no-files-found: error

    - name: Upload Static Web App Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBRGBDump.Web.Static
        path: publish/GBRGBDump.Web.Static/**
        if-no-files-found: error

  build-gbrgbdump:
    if: false # Legacy job disabled for now
    runs-on: ubuntu-latest
    # Avoid running time-expensive matrix build if the GUI fails
    needs: build-gbrgbdump-gui
    strategy:
        matrix:
            include:
                - { runtime: 'win-x64', output: 'win-x64' }
                - { runtime: 'linux-x64', output: 'linux-x64' }
                - { runtime: 'linux-arm', output: 'linux-arm' }
                - { runtime: 'linux-arm64', output: 'linux-arm64' }
    env:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        global-json-file: ./global.json
        dotnet-version: '10.0.202'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Restore dependencies
      run: dotnet restore --locked-mode ./GBRGBDump.slnx

    - name: Add NuGet package source
      run : |
        dotnet nuget add source --username ${{ env.NUGET_OWNER }} --store-password-in-clear-text --password ${{ env.NUGET_APIKEY }} --name maddo-github "https://nuget.pkg.github.com/${{ env.NUGET_OWNER }}/index.json"

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.2
      with:
        versionSpec: '6.0.x'

    - name: Determine Version
      id: version_step # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.1.2

    - name: Update Version
      uses: gittools/actions/gitversion/command@v3.1.2
      with:
        arguments: /updateprojectfiles

    - name: Build GBRGBDump
      run: |
        dotnet publish ./GBRGBDump/GBRGBDump.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true --output publish/GBRGBDump/${{ matrix.output }}

    - name: Build GBRGBDump Web
      run: |
        dotnet publish ./GBRGBDump.Web/GBRGBDump.Web.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true --output publish/GBRGBDump-web/${{ matrix.output }}

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBRGBDump-web-${{ matrix.output }}
        path: publish/GBRGBDump-web/${{ matrix.output }}/**
        if-no-files-found: error

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBRGBDump-${{ matrix.output }}
        path: publish/GBRGBDump/${{ matrix.output }}/**
        if-no-files-found: error

    # Build and publish docker image
    - name: Build and publish Docker
      if: matrix.runtime != 'win-x64' # Skip Docker build for win-x64
      run: |
          LOWERCASE_OWNER=$(echo "${{ env.NUGET_OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker login --username ${{ env.NUGET_OWNER }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

          # Map architectures
          ARCH=""
          if [ "${{ matrix.runtime }}" = "linux-x64" ]; then
            ARCH="AMD64"
          elif [ "${{ matrix.runtime }}" = "linux-arm" ]; then
            ARCH="ARM32V7"
          elif [ "${{ matrix.runtime }}" = "linux-arm64" ]; then
            ARCH="ARM64V8"
          fi
          LOWERCASE_ARCH=$(echo "$ARCH" | tr '[:upper:]' '[:lower:]')

          docker build -f ./GBRGBDump.Web/Dockerfile . --build-arg ARCH=$ARCH --tag ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ steps.version_step.outputs.fullSemVer }}-$ARCH
          docker push ghcr.io/$LOWERCASE_OWNER/gbrgbdump --all-tags
      # TODO: tag as latest only if it's a release

  publish-release:
    needs: [build-gbrgbdump-gui]
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
    steps:
    - uses: dawidd6/action-download-artifact@v6
      with:
        path: artifacts
        skip_unpack: true
        if_no_artifact_found: fail
        workflow_conclusion: ""
        name: ^(?!.*nuget).*
        name_is_regexp: true
    # Debug step
    - name: Display structure of downloaded files
      run: ls -R

    # - name: Create Release
    #   id: create_release
    #   uses: elgohr/Github-Release-Action@v5
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag: ${{ github.run_number }}
    #     title: Release ${{ github.run_number }}

    # - name: Minor version for each merge
    #   id: AutoTagger
    #   uses: anothrNick/github-tag-action@1.36.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     WITH_V: true
    #     CUSTOM_TAG: ${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      
      with:
        files: ./artifacts/**
        tag_name: ${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}
        # upload_url: ${{ steps.create_release.outputs.upload_url }}
        # asset_path: ./artifacts
        # asset_name: Release-Assets.zip
        # asset_content_type: application/zip

    - name: Add NuGet package source
      run : |
        dotnet nuget add source --username ${{ env.NUGET_OWNER }} --store-password-in-clear-text --password ${{ env.NUGET_APIKEY }} --name maddo-github "https://nuget.pkg.github.com/${{ env.NUGET_OWNER }}/index.json"

    - name: Download the nuget artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        path: nuget
        skip_unpack: false
        if_no_artifact_found: fail
        workflow_conclusion: ""
        name: .*nuget.*
        name_is_regexp: true

    # Publish packages
    - name: Publish NuGet package
      run: |
        for file in $(find "nuget" -type f -name "*.nupkg"); do
          dotnet nuget push "$file" --api-key "${{ env.NUGET_APIKEY }}" --source maddo-github --skip-duplicate
        done

    # Merge Docker Packages
    # Build and publish docker image
    - name: Build and publish Docker
      if: false # Legacy docker release disabled for now
      run: |
          LOWERCASE_OWNER=$(echo "${{ env.NUGET_OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker login --username ${{ env.NUGET_OWNER }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

          docker manifest create ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }} \
          -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-amd64 \
          -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-arm32v7 \
          -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-arm64v8

          # docker manifest push ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}

          # docker manifest create ghcr.io/$LOWERCASE_OWNER/gbrgbdump:latest \
          # -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-amd64 \
          # -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-arm32v7 \
          # -- amend ghcr.io/$LOWERCASE_OWNER/gbrgbdump:${{ needs.build-gbrgbdump-gui.outputs.fullSemVer }}-arm64v8

          # docker manifest push ghcr.io/$LOWERCASE_OWNER/gbrgbdump:latest
      # TODO: tag as latest only if it's a release


    